name: star_trail
description: Increase Your Focus
full_description: 'star_trail is a focus timer app that helps you balance your focus and break time.'
android: false
iOS: https://apps.apple.com/us/app/star-trail/id1524263644
web: false
screenshots:
  - iPhone65_1.png
  - iPhone65_2.png
  - iPhone65_3.png
  - iPhone65_4.png
  - iPhone65_5.png
producthunt: false
companies: false
